src/Entity/Chikowa/Tontine.php
<?php

namespace App\Entity\Chikowa;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\Chikowa\TontineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TontineRepository::class)
 * @UniqueEntity(
 *     fields={"libelle","association"},
 *     errorPath="libelle"
 * )
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"read"}},
 *     "denormalization_context"={"groups"={"write"}}
 * })
 */
class Tontine
{

    const  PAYEMENT_FREQUENCE=[
        'Mensuel'=>'M',
        'Tous les 10 jours'=>'10D',
        'Hebdomadaire'=>'W'
    ];

    const PAYEMENT_FREQUENCE_KEYS=['M','10D','W'];

    const TYPE_TONTINE=[
        'Tontine rotative'=>'rotative',
        'Tontine à accumulation'=>'accumulation'
    ];
    const TYPE_TONTINE_ROTATIVE='rotative';
    const TYPE_TONTINE_ACCUMULATION='accumulation';
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="string")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(min="3",max="100",groups={"Default", "edit"})
     * @Assert\NotBlank(groups={"Default", "edit"})
     */
    private $libelle;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(groups={"Default", "edit"})
     * @Assert\GreaterThan(value="0",groups={"Default", "edit"})
     */
    private $montantParMembre;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\Choice(choices=Tontine::PAYEMENT_FREQUENCE_KEYS,groups={"Default", "edit"})
     */
    private $frequencePaiement;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual(value="today" ,groups={"Default"})
     */
    private $dateDebut;

    /**
     * @ORM\ManyToOne(targetEntity=Association::class, inversedBy="tontines")
     */
    private $association;

    /**
     * @ORM\OneToMany(targetEntity=Inscription::class, mappedBy="tontine",cascade={"persist"}))
     * @ORM\OrderBy({"positionRecuperation" = "ASC"})
     * @Assert\Valid()
     */
    private $inscriptions;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $tontineType;

    public function __construct()
    {
        $this->dateDebut=new \DateTime();
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(?string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getMontantParMembre(): ?float
    {
        return $this->montantParMembre;
    }

    public function setMontantParMembre(float $montantParMembre): self
    {
        $this->montantParMembre = $montantParMembre;

        return $this;
    }

    public function getFrequencePaiement(): ?string
    {
        return $this->frequencePaiement;
    }
    public function getFrequencePaiementLibelle(): ?string
    {
        return array_flip(self::PAYEMENT_FREQUENCE)[$this->frequencePaiement];
    }

    public function setFrequencePaiement(string $frequencePaiement): self
    {
        $this->frequencePaiement = $frequencePaiement;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): self
    {
        $this->association = $association;

        return $this;
    }

    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $inscription->setTontine($this);
            $this->inscriptions[] = $inscription;
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->contains($inscription)) {
            $this->inscriptions->removeElement($inscription);
            // set the owning side to null (unless already changed)
            if ($inscription->getTontine() === $this) {
                $inscription->setTontine(null);
            }
        }

        return $this;
    }

    public function getTontineType(): ?string
    {
        return $this->tontineType;
    }

    public function setTontineType(string $tontineType): self
    {
        $this->tontineType = $tontineType;

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

src/Form/Chikowa/AssociationAddMembreType.php
<?php

namespace App\Form\Chikowa;

use App\Entity\Chikowa\Association;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AssociationAddMembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('membres', CollectionType::class,array(
                'entry_type'=>MembreType::class,
                'label' => false,
                'entry_options'=>['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Association::class,
        ]);
    }
}

src/Form/Chikowa/InscriptionType.php
<?php

namespace App\Form\Chikowa;

use App\Entity\Chikowa\Inscription;
use App\Entity\Chikowa\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tontine', null,[
                'attr'=>['class'=>'d-none']
            ])
            ->add('positionRecuperation', IntegerType::class)
            ->add('membre',MembreType::class,
                [
                    'data_class' => Membre::class,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Form/Chikowa/MembreType.php
<?php

namespace App\Form\Chikowa;

use App\Entity\Chikowa\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('telephone', TelType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/Chikowa/AssociationController.php
<?php

namespace App\Controller\Chikowa;

use App\Entity\Chikowa\Association;
use App\Entity\Chikowa\Membre;
use App\Entity\ChikowaUser;
use App\Form\Chikowa\TontineAddMembreType;
use App\Form\Chikowa\AssociationType;
use App\Form\Chikowa\MembreType;
use App\Repository\Chikowa\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/chikowa/association")
 */
class AssociationController extends AbstractController
{
    /**
     * @Route("/", name="chikowa_association_index", methods={"GET"})
     */
    public function index(AssociationRepository $associationRepository): Response
    {
        /** @var ChikowaUser $user */
        $user = $this->getUser();
        if ($user->getAssociations()->isEmpty()) {
            $this->redirectToRoute('chikowa_association_new');
        }
        return $this->render('chikowa/association/choice_association_index.html.twig', [
            'associations' => $user->getAssociations(),
        ]);

    }

    /**
     * @Route("/new", name="chikowa_association_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $association = new Association();
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $localisation = $association->getLocalisation();
            $address = explode("-->", $localisation);
            if ($address) {
                $association->setLocalisation($address[0]);
                $association->setPlaceId($address[1]);
            }
            $association->addGestionaire($this->getUser());
            $entityManager->persist($association);
            $entityManager->flush();

            $this->addFlash(
                'success',
                sprintf("L'asociation %s est enregistré avec succès", $association->getLibelle())
            );
            return $this->redirectToRoute('chikowa_dashboard');
        }
        return $this->render('chikowa/association/new.html.twig', [
            'association' => $association,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chikowa_association_show", methods={"GET"})
     */
    public function show(Association $association): Response
    {
        return $this->render('chikowa/association/show.html.twig', [
            'association' => $association,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="chikowa_association_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Association $association): Response
    {
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $localisation = $association->getLocalisation();
            $address = explode("-->", $localisation);
            dump($address);
            if ($address) {
                $association->setLocalisation($address[0]);
                $association->setPlaceId($address[1]);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chikowa_association_index');
        }

        return $this->render('chikowa/association/edit.html.twig', [
            'association' => $association,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chikowa_association_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Association $association): Response
    {
        if ($this->isCsrfTokenValid('delete' . $association->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($association);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chikowa_association_index');
    }

}

src/Controller/Chikowa/DashboardController.php
<?php

namespace App\Controller\Chikowa;

use App\Entity\ChikowaUser;
use App\Repository\Chikowa\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    /**
     * @Route("/chikowa/", name="chikowa_dashboard_index")
     * @Route("/chikowa/dashboard", name="chikowa_dashboard")
     * @return Response
     */
    public function index()
    {
        /** @var ChikowaUser $currentUser */
        $currentUser=$this->getUser();
        $nombreTontine =0;
        $nombreMembre=0;

        foreach ($currentUser->getAssociations() as $association){
            $nombreTontine+=$association->getTontines()->count();
            foreach ($association->getTontines() as $tontine) {
                $nombreMembre += $tontine->getInscriptions()->count();
            }
        }

        return $this->render('chikowa/dashboard/index.html.twig', [
            'associations' => $currentUser->getAssociations(),
            'nombreTontine'=>$nombreTontine,
            'nombreMembre'=>$nombreMembre
        ]);
    }
}

src/Controller/Chikowa/InscriptionController.php
<?php

namespace App\Controller\Chikowa;

use App\Entity\Chikowa\Association;
use App\Entity\Chikowa\Inscription;
use App\Entity\Chikowa\Tontine;
use App\Form\Chikowa\InscriptionType;
use App\Repository\Chikowa\InscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * @Route("/chikowa/inscription")
 */
class InscriptionController extends AbstractController
{
    /**
     * @Route("/", name="chikowa_inscription_index", methods={"GET"})
     * @param InscriptionRepository $inscriptionRepository
     * @return Response
     */
    public function index(InscriptionRepository $inscriptionRepository): Response
    {
        return $this->render('chikowa/inscription/index.html.twig', [
            'inscriptions' => $inscriptionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/tontine/{id}/new", name="chikowa_inscription_new", methods={"GET","POST"})
     * @param Tontine $tontine
     * @param Request $request
     * @return Response
     */
    public function inscrireMembre(Tontine $tontine ,Request $request): Response
    {
        $inscription = new Inscription();
        $inscription->setTontine($tontine);
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist(s);
            $entityManager->flush();

            return $this->redirectToRoute('chikowa_inscription_index');
        }

        return $this->render('chikowa/inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chikowa_inscription_show", methods={"GET"})
     */
    public function show(Inscription $inscription): Response
    {
        return $this->render('chikowa/inscription/show.html.twig', [
            'inscription' => $inscription,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="chikowa_inscription_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Inscription $inscription): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chikowa_inscription_index');
        }

        return $this->render('chikowa/inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chikowa_inscription_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Inscription $inscription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inscription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($inscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chikowa_inscription_index');
    }
}

templates/chikowa/tontine/_delete_form.html.twig
<form method="post" action="{{ path('chikowa_tontine_delete', {'id': tontine.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tontine.id) }}">
    <button class="btn">Delete</button>
</form>

templates/chikowa/tontine/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_row(form.libelle,{
        'label': 'Donnez un nom à votre chikowa',
        'attr':{'placeholder': 'example : Chikowa des Mamams'},
        'autofocus': true
    }) }}
    {{ form_row(form.montantParMembre,{
        'label': 'Le montant payé par membre',
        'attr':{'placeholder': 'example : 200'},

    }) }}
    {{ form_row(form.tontineType,{
        'label': 'Le type',
        'attr':{'data-select' : 'true'}
    }) }}

    {{ form_row(form.frequencePaiement,{
        'label': 'La fréquence de paiement',
        'attr':{'data-select' : 'true'}
    }) }}

{{ form_row(form.dateDebut,{
    'label': 'Date de démarrage'
}) }}
<div class="d-flex justify-content-between">
    <a class="btn btn-outline-orange" href="{{ path('chikowa_tontine_index') }}"> <i class="fa fa-arrow-left fa-align-left"> </i> back to list</a>
    <button class="btn btn-orange"><i class="fa fa-save fa-align-left"> </i> {{ button_label|default('Enregistrer') }}</button>
</div>
{{ form_end(form) }}

templates/chikowa/tontine/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Tontine - {{ tontine.libelle}} {% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="col-6">
                    <h1 class="h2 text-orange mb-3">Modification tontine : {{ tontine.libelle}}  </h1>
                    {{ include('chikowa/tontine/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/chikowa/tontine/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Tontines par associations{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="h3 text-orange">Mes Tontines par associations</h1>
        <div class="accordion" id="accordionAssociation">
            {% for association in associations %}
                <div class="card">
                    <div class="card-header bg-orange d-flex justify-content-between" id="heading-{{ association.id }}">
                        <h3 class="mb-0 w-100">
                            <a class="text-light btn-block text-left text-decoration-none" type="button" data-toggle="collapse" data-target="#collapse-{{ association.id }}" aria-expanded="true" aria-controls="collapse-{{ association.id }}">
                                {{ association.libelle }}
                            </a>
                        </h3>
                    </div>

                    <div id="collapse-{{ association.id }}" class="collapse {{ associations.first.id==association.id? "show" }}" aria-labelledby="heading-{{ association.id }}" data-parent="#accordionAssociation">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Libelle</th>
                                    <th>Montant Par Membre</th>
                                    <th>Frequence Paiement</th>
                                    <th>Nombre d'inscrits</th>
                                    <th>actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for tontine in association.tontines %}
                                    <tr>
                                        <td>{{ tontine.libelle }}</td>
                                        <td>
                                            <span class="badge badge-danger rounded-pill font-weight-bolder">{{ tontine.montantParMembre | format_currency('EUR') }}</span>
                                        </td>
                                        <td>
                                            <span class="badge badge-info">{{ tontine.frequencePaiementLibelle }}</span>
                                        </td>
                                        <td>
                                            <span class="badge badge-secondary">{{ tontine.inscriptions|length }}</span>
                                        </td>
                                        <td>
                                            <div class="btn-group-sm">
                                            <a class="btn btn-sm btn-orange" href="{{ path('chikowa_tontine_show', {'id': tontine.id}) }}">
                                                voir
                                            </a>
                                            <a class="btn btn-sm btn-outline-success" href="{{ path('chikowa_tontine_edit', {'id': tontine.id}) }}">modifier</a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr style="border-top-style:hidden;">
                                        <td colspan="6" class="text-right">
                                            {% if not association.tontines.empty %}
                                                <button data-tontine="{{ tontine.id }}"
                                                        data-tontine-libelle="{{ tontine.libelle }}"
                                                        data-association="{{ association.id  }}"
                                                        data-url="{{ path('chikowa_inscription_liste', {'id': tontine.id}) }}"
                                                        data-association-libelle="{{ association.libelle }}"
                                                        data-toggle="modal" data-target="#modal-afficher-participants-tontine"
                                                        class="btn rounded-pill btn-outline-info">
                                                    <i class="fas fa-user-friends"></i> Afficher les participants
                                                </button>
                                                <a class="btn rounded-pill btn-info" href="{{ path('chikowa_inscription_new',{'id':tontine.id }) }}">
                                                    <i class="fas fa-user-plus"></i> Inscrire un membre
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="6">no records found</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="6" class="text-right">
                                        <a class="btn rounded-pill btn-orange" href="{{ path('chikowa_tontine_creation_association',{'id':association.id }) }}">
                                            <i class="fa fa-euro-sign"></i> Creer une nouvelle tontine
                                        </a>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modal-afficher-participants-tontine" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-orange" id="modalLabel">Participant tontine</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/chikowa/tontine/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tontine{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div class="col-6">
                <h1 class="h2 text-orange mb-3">Je crée une Tontine</h1>
                {{ include('chikowa/tontine/_form.html.twig') }}
            </div>
        </div>
    </div>
    <a href="{{ path('chikowa_tontine_index') }}">back to list</a>
</div>
{% endblock %}

templates/chikowa/tontine/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tontine{% endblock %}

{% block body %}
    <h1>Tontine</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tontine.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ tontine.libelle }}</td>
            </tr>
            <tr>
                <th>MontantParMembre</th>
                <td>{{ tontine.montantParMembre }}</td>
            </tr>
            <tr>
                <th>FrequencePaiement</th>
                <td>{{ tontine.frequencePaiement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('chikowa_tontine_index') }}">back to list</a>

    <a href="{{ path('chikowa_tontine_edit', {'id': tontine.id}) }}">edit</a>

    {{ include('chikowa/tontine/_delete_form.html.twig') }}
{% endblock %}